# Generated by Django 4.2.13 on 2026-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='do_min',
            field=models.FloatField(default=4.0, verbose_name='溶氧下限 (mg/L)'),
        ),
        migrations.AddField(
            model_name='pond',
            name='ph_max',
            field=models.FloatField(default=9.0, verbose_name='pH 上限'),
        ),
        migrations.AddField(
            model_name='pond',
            name='ph_min',
            field=models.FloatField(default=7.0, verbose_name='pH 下限'),
        ),
        migrations.AddField(
            model_name='pond',
            name='salinity_max',
            field=models.FloatField(default=35, verbose_name='鹽度上限 (ppt)'),
        ),
        migrations.AddField(
            model_name='pond',
            name='salinity_min',
            field=models.FloatField(default=15, verbose_name='鹽度下限 (ppt)'),
        ),
        migrations.AddField(
            model_name='pond',
            name='temp_max',
            field=models.FloatField(default=32, verbose_name='水溫上限 (°C)'),
        ),
        migrations.AddField(
            model_name='pond',
            name='temp_min',
            field=models.FloatField(default=24, verbose_name='水溫下限 (°C)'),
        ),
    ]
