# Generated by Django 4.2.13 on 2026-06-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0002_pond_do_min_pond_ph_max_pond_ph_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to=settings.AUTH_USER_MODEL, verbose_name='養殖場主人'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='pond',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_pond_name_per_owner'),
        ),
    ]
