# Generated by Django 4.2.13 on 2026-04-12 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIoTProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='專案名稱')),
                ('description', models.TextField(verbose_name='專案說明')),
                ('tech_stack', models.CharField(blank=True, max_length=300, verbose_name='技術棧')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aiot/', verbose_name='專案圖片')),
                ('demo_url', models.URLField(blank=True, verbose_name='展示連結')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'AIoT 專案',
                'verbose_name_plural': 'AIoT 專案列表',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('subject', models.CharField(max_length=200, verbose_name='主旨')),
                ('message', models.TextField(verbose_name='訊息內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
            ],
            options={
                'verbose_name': '聯絡訊息',
                'verbose_name_plural': '聯絡訊息列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('date', models.DateField(verbose_name='活動日期')),
                ('location', models.CharField(default='水井村風雲客棧', max_length=200, verbose_name='活動地點')),
                ('category', models.CharField(choices=[('activity', '體驗活動'), ('aiot', 'AIoT 展示'), ('usr', 'USR 成果'), ('workshop', '工作坊'), ('other', '其他')], default='activity', max_length=20, verbose_name='類別')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='活動圖片')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首頁精選')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動列表',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='新聞標題')),
                ('source', models.CharField(max_length=100, verbose_name='來源')),
                ('url', models.URLField(blank=True, verbose_name='新聞連結')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('published_date', models.DateField(verbose_name='發布日期')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='新聞圖片')),
            ],
            options={
                'verbose_name': '相關新聞',
                'verbose_name_plural': '新聞列表',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='故事標題')),
                ('content', models.TextField(verbose_name='故事內容')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者/來源')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='故事圖片')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='發布日期')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首頁精選')),
            ],
            options={
                'verbose_name': '在地故事',
                'verbose_name_plural': '在地故事列表',
                'ordering': ['-published_date'],
            },
        ),
    ]
